{{- range $svcName, $svc := .Values }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $svc.name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      protocol: TCP
---
{{- end }}
